spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_university
    username: somegreatusername
    password: somegreatpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: NONE
    banner-mode: off